### PR TITLE
Only upload packages associated with current package name batch

### PR DESCRIPTION
**Pull request by mitchhentges**

### CODE REVIEW

**Comment by mitchhentges** [comment]
Really, coveralls? How did this lower our coverage? :thinking: :angry: :smile:

**Comment by JohanLorenzo** [comment]
That might be because your PR isn't branched out of the latest master, where there might have been a coverage decrease.

**Comment by mitchhentges** [comment]
Hmm, this is up-to-date with `master`. :thinking: 
Plus a failing Travis build? gosh dang darn it

**Comment by JohanLorenzo** [comment]
Don't worry about the Travis failure. @flodolo warned me the certificate of https://l10n.mozilla-community.org/ hasn't been renewed. Could you mark these tests as skipped, @mitchhentges ?

**Comment by JohanLorenzo** [comment]
I've got some news. @flodolo told me he fixed the certificate issue. We won't need to skip the tests package anymore 😃

**Pull request merged**
